


        
        builds:
                - main: ./main.go
                  goos:
                              - linux
                                    - darwin
                                          - windows
                  goarch:
                              - 386
                                    - amd64
                                          - arm
                                                - arm64
                  env:
                          - CGO_ENABLED=0
